title: 0CBH0
description: RE & Bio.
author: 0CBH0
logo: https://avatars2.githubusercontent.com/u/10806069?s=460&v=4
github: https://github.com/0CBH0
about: RE & Bio.

baseurl: "https://0CBH0.github.io"
url: "https://0CBH0.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-149466812-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
